### ISSUE TITLE
[Repo Request]: hyprland-py

### ISSUE THREAD

**Issue by flickowoa** [hyprland-community/submissions#1]
### What do you want it to be named?

hyprland-py

### What do you want to use it for?

a library to work as an alternative to hyprland.conf configured in python ( something like lua and awesome api)
[github.com/flick0/hyprland-py](https://github.com/flick0/hyprland-py)

**Comment by yavko** [comment]
You have been invited to the org, just transfer the repo, and everything should be done!

**Comment by yavko** [comment]
Don't forget to also add a maintainer thing to the repo desc, like so `[maintainer=@flick0]`

**Comment by yavko** [comment]
Okay made you admin just add that to desc and everything should be done!

*this desc*
![image](https://user-images.githubusercontent.com/15178513/209421929-932468df-f50b-432d-9835-d2dc2eea2cc5.png)
