### ISSUE TITLE
[Repo Request]: https://github.com/fdev31/hpr-scratcher

### ISSUE THREAD

**Issue by fdev31** [hyprland-community/submissions#2]
### What do you want it to be named?

hpr-scratcher

### What do you want to use it for?

Copy code of https://github.com/fdev31/hpr-scratcher

**Comment by yavko** [comment]
Thanks for the submission! I've sent you an invitation to join the org, once you accept it move it to the org, I'll close the issue.

**Comment by yavko** [comment]
Looks good! Sorry for the late response, but also needs maintainer metadata in the desc ex. `[maintainer=@fdev31]`
