### ISSUE TITLE
[Repo Request]: hypr-trans

### ISSUE THREAD

**Issue by jlaunay** [hyprland-community/submissions#4]
### What do you want it to be named?

hypr-trans

### What do you want to use it for?

https://github.com/jlaunay/hypr-trans

**Comment by yavko** [comment]
Sorry for not responding earlier, but I sent an invitation, to transfer the repo use this button in repo settings
![image](https://github.com/hyprland-community/submissions/assets/15178513/eb5976f8-3103-4b77-bcc3-ac504d95ad78)
