### ISSUE TITLE
[Repo Request]: hypr-binds

### ISSUE THREAD

**Issue by gvolpe** [hyprland-community/submissions#7]
### What do you want it to be named?

hypr-binds

### What do you want to use it for?

A Hyprland keybinds helper using wofi (it parses the output of hyprctl binds), example:

![demo](https://raw.githubusercontent.com/gvolpe/nix-config/master/imgs/hypr-binds.png)

**Comment by gvolpe** [comment]
I have a personal repo for this, happy to move it over to the community org if accepted: https://github.com/gvolpe/hypr-binds

**Comment by NotAShelf** [comment]
I would be happy to welcome hypr-binds to Hyprland-community, though I would also consider non-nix support a priority if not a blocker to get in - we are not a Nix-only community, and the project is more likely to be adopted if it can be used by others outside of Nix users.

**Comment by gvolpe** [comment]
@NotAShelf I would consider providing a simple bash script that only relies on `jq` and `wofi` for non-Nix users (it will be the same you currently get by running it via `nix run github:gvolpe/hypr-script`).

It won't be configurable though, as that would require a proper command-line client, but users should be able to copy it and adapt it to their needs. Would that be acceptable?

**Comment by NotAShelf** [comment]
That sounds agreeable.

**Comment by gvolpe** [comment]
@NotAShelf done: https://github.com/gvolpe/hypr-binds/releases/tag/v0.0.1

Needs to be better documented, and I can also add Rofi support, but I think this is a good start :)

**Comment by gvolpe** [comment]
@NotAShelf is that good enough as a starting point? If so, I'm not sure what the process for transferring the repo is, I think I may need access to the `hyprland-community` org?

**Comment by NotAShelf** [comment]
Yes, sorry for the delay - I could not onboard you due to limitations of Github mobile. Hoped Yavko would be able to, but seems we were both busy.

I sent you an invite, you can transfer the repository to the org once you accept.

**Comment by gvolpe** [comment]
Thank you! It's been transferred: https://github.com/hyprland-community/hypr-binds

I just finished work and got some free time (no wife around 😄 ) so I'll get some docs up for non-Nix users.
