### ISSUE TITLE
[Repo Request]: Nexus

### ISSUE THREAD

**Issue by lordxexsteros** [hyprland-community/submissions#8]
### What do you want it to be named?

Nexus

### What do you want to use it for?

#  Nexus 1.1.0-beta
### It is the hyprland rice **built on top of @flick0's **aurora**

> It is still a work in progress and i am 12 years old

[Nexus-main.zip](https://github.com/user-attachments/files/17337913/Nexus-main.zip)

**Comment by NotAShelf** [comment]
Thank you for the submission, unfortunately we will not be accepting it.

1. We do not accept personal configurations, this organization is for software and tools for Hyprland.

2. Please do not send obscure zipfiles over the internet. Most people will never bother to open those, and some will assume malicious intent.

**Comment by lordxexsteros** [comment]
OK fine
