### ISSUE TITLE
[Repo Request]: lordxexsteros

### ISSUE THREAD

**Issue by lordxexsteros** [hyprland-community/submissions#9]
### What do you want it to be named?

Nexus

### This is not my personal rice!
# Project-Nexus
## Project Nexus is an eazy to configure, simple and beginner-friendly starter-pack inspired by @flick0's aurora theme and @mylinuxforwork's hypr-starter. It has a build in easy installer so that you dont have to configure the files maually. It can also be used by professionals for their hyprland experiments with files setup in a clean and easy way to configure.
# To learn more visit - [About Project-Nexus](https://github.com/lordxexsteros/Nexus)
>This is still a WIP

**Comment by yavko** [comment]
https://github.com/hyprland-community/submissions/issues/8#issuecomment-2408272974

**Comment by lordxexsteros** [comment]
This is not my personal files!!

**Comment by yavko** [comment]
> This is not my personal files!! 

Still a rice, rices can be submitted to the theme repository. Rices/themes are not tools or something else we are accepting.
